version: '3.9'

services:
  db:
    image: postgres:14.2
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
      - POSTGRES_HOST=127.0.0.1
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - db_network
    restart: unless-stopped
  redis:
    image: redis:7.0.0
    networks:
      - redis_network
    restart: unless-stopped
  api:
    build:
      context: .
    command: bash -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn api.wsgi -c gunicorn_conf.py
      "
    environment:
      - DATABASE_URL=psql://user:password@db:5432/db
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    volumes:
      - static_volume:/api/static
      - profile_volume:/api/profile
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    networks:
      - db_network
      - redis_network
      - nginx_network
    restart: unless-stopped
  web:
    image: node:14.0.0
    volumes:
      - web_volume:/build
  nginx:
    image: nginx:1.21.6
    depends_on:
      - api
      - web
    env_file:
      - .env
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf
      - API_DOMAIN=api.local.dev
      - WEB_DOMAIN=local.dev
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/static
      - web_volume:/html
      - ./nginx.conf.conf:/etc/nginx/templates/nginx.conf.conf
      - ./certs:/certs
    networks:
      - nginx_network
    restart: unless-stopped
  celery:
    build:
      context: .
    command: celery -A api worker -c 1 -P gevent -l info
    environment:
      - DATABASE_URL=psql://user:password@db:5432/db
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - nginx
    networks:
      - db_network
      - redis_network
    restart: unless-stopped
  celery_beat:
    build:
      context: .
    command: celery -A api beat -S django -l info
    environment:
      - DATABASE_URL=psql://user:password@db:5432/db
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - celery
    networks:
      - db_network
      - redis_network
    restart: unless-stopped

volumes:
  db_volume:
  web_volume:
  static_volume:
  profile_volume:

networks:
  db_network:
  redis_network:
  nginx_network:
