version: '3.9'

services:
  db:
    image: postgres:14.2
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
      - POSTGRES_HOST=127.0.0.1
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - db_network
    restart: unless-stopped
  redis:
    image: redis:7.0.0
    networks:
      - redis_network
    restart: unless-stopped
  api:
    build:
      context: .
    command: bash -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        python manage.py runserver 0.0.0.0:8000
      "
    environment:
      - DATABASE_URL=psql://user:password@db:5432/db
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    volumes:
      - static_volume:/api/static
      - profile_volume:/api/profile
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    networks:
      - db_network
      - redis_network
    restart: unless-stopped
  celery:
    build:
      context: .
    command: celery -A api worker -c 1 -P gevent -l info
    environment:
      - DATABASE_URL=psql://user:password@db:5432/db
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - api
    networks:
      - db_network
      - redis_network
    restart: unless-stopped
  celery_beat:
    build:
      context: .
    command: celery -A api beat -S django -l info
    environment:
      - DATABASE_URL=psql://user:password@db:5432/db
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - celery
    networks:
      - db_network
      - redis_network
    restart: unless-stopped

volumes:
  db_volume:
  static_volume:
  profile_volume:

networks:
  db_network:
  redis_network:
