name: Backup media

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  deploy:
    runs-on: [self-hosted, nft-marketplace]
    steps:
    - name: Create dirs
      run: |
        cd ~
        mkdir -p nft-marketplace/media || true
        sudo chown www nft-marketplace/
        cd nft-marketplace
        mkdir -p backups/media || true
    - name: Make backup
      run: cp -r media backups/media/$(date +"%Y-%m-%dT%H:%M:%S")
    - name: Clean old backups
      run: |
        cd backups/media
        ls -t | sed -e '1,5d' | xargs rm -rf
