name: "Call: update PRs"

on:
  workflow_call:

permissions: write-all

jobs:
  update:
    runs-on: ubuntu-22.04
    steps:
      - uses: pascalgn/automerge-action@v0.15.5
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          UPDATE_LABELS: ""
