name: CD stage

on:
  workflow_call:

jobs:
  deploy:
    runs-on: [self-hosted, nft-marketplace]
    steps:
    - uses: actions/checkout@v3.1.0
      with:
        repository: codepandoradev/nft-marketplace-api
        clean: false
    - name: Deploy stage environment
      run: 
        |
        docker rmi nft-marketplace-stage-nginx -f || true
        docker-compose -p nft-marketplace-stage -f docker/docker-compose.stage.yml up --force-recreate --build -d
