name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy_dev:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        clean: false
    - name: Deploy dev environment
      run: docker compose -f docker/docker-compose.dev.yml up --force-recreate --build -d
