name: CD

on:
  push:
    branches: [ "master" ]

jobs:
  deploy_dev:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3.1.0
      with:
        clean: false
    - name: Deploy stage environment
      run: 
        |
        docker rmi envy42/nft-marketplace-web -f || true
        docker-compose -p nft-marketplace-stage -f docker/docker-compose.stage.yml up --force-recreate --build -d
