name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  tests:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: echo $USER
      # run: docker-compose -f docker/docker-compose.test.yml run api
