name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: docker-compose -f docker/docker-compose.test.yml run api
  deploy_dev:
    runs-on: self-hosted
    needs: tests
    steps:
    - uses: actions/checkout@v3
    - name: Deploy dev environment
      run: docker-compose -f docker/docker-compose.dev.yml up --force-recreate --build
