name: Push master

on:
  push:
    branches:    
      - 'master'

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  cd:
    uses: codepandoradev/nft-marketplace-cicd/.github/workflows/cd-stage.yml@main
    needs: [ci]
