name: On push in the master branch

on:
  push:
    branches:    
      - 'master'

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
  cd:
    uses: ./.github/workflows/cd-stage.yml
    needs: [ ci ]
  release-draft:
    uses: ./.github/workflows/call-release_draft.yml
    secrets: inherit
    needs: [ ci ]
